//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.09 at 07:31:17 AM IST 
//


package org.info2000.policy;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for address complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="address">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="PostalHomeAddress" type="{http://www.info2000.org/Policy}PostalHomeAddress"/>
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PostalOfficeAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "address", propOrder = {
    "postalHomeAddress",
    "email",
    "postalOfficeAddress"
})
public class Address
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlElement(name = "PostalHomeAddress")
    protected PostalHomeAddress postalHomeAddress;
    protected String email;
    @XmlElement(name = "PostalOfficeAddress")
    protected String postalOfficeAddress;

    /**
     * Gets the value of the postalHomeAddress property.
     * 
     * @return
     *     possible object is
     *     {@link PostalHomeAddress }
     *     
     */
    public PostalHomeAddress getPostalHomeAddress() {
        return postalHomeAddress;
    }

    /**
     * Sets the value of the postalHomeAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link PostalHomeAddress }
     *     
     */
    public void setPostalHomeAddress(PostalHomeAddress value) {
        this.postalHomeAddress = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the postalOfficeAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostalOfficeAddress() {
        return postalOfficeAddress;
    }

    /**
     * Sets the value of the postalOfficeAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostalOfficeAddress(String value) {
        this.postalOfficeAddress = value;
    }

}
