//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.09 at 07:31:17 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.info2000.org/Policy", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.info2000.policy;
